---
title: "hw7lab7"
author: "Chan, Kim Fai"
date: "11/7/2021"
output: html_document
---


```{r}
setwd("~/Desktop/jeff's documents/Master of Economics in CCNY/ECONOMETRICS ECO B2000/homework 7 lab 7")
load("~/Desktop/jeff's documents/Master of Economics in CCNY/ECONOMETRICS ECO B2000/homework 7 lab 7/Household_Pulse_data 11072021.rdata")
attach(Household_Pulse_data)
summary(Household_Pulse_data)


#For the simple linear regression (glm function) it is not necessary to set the variables in a data frame. Although for the new models we are using it will be necessary. Below is the data frame with the list of variables set to have the same number of rows with unique row names in the class “data.frame”. Because it includes a matrix it will force the columns names to have unique results.

Household_Pulse_data$vaxx <- (Household_Pulse_data$RECVDVACC == "yes got vaxx")
summary(Household_Pulse_data$vaxx)
table1 <- table(Household_Pulse_data$vaxx)
table1
prop.table(table1)
use_varb <- (Household_Pulse_data$TBIRTH_YEAR >= 1956) & (Household_Pulse_data$TBIRTH_YEAR <= 1996)
dat_use1 <- subset(Household_Pulse_data,use_varb)
summary(dat_use1)
d_educ <- data.frame(model.matrix(~ dat_use1$EEDUC))
summary(d_educ)
levels(dat_use1$EEDUC)
d_marstat <- data.frame(model.matrix(~ dat_use1$MS))
summary(d_marstat)
levels(dat_use1$MS)
d_race <- data.frame(model.matrix(~ dat_use1$RRACE))
summary(d_race)
levels(dat_use1$RRACE)
d_hispanic <- data.frame(model.matrix(~ dat_use1$RHISPANIC))
summary(d_hispanic)
levels(dat_use1$RHISPANIC)
d_gender <- data.frame(model.matrix(~ dat_use1$GENID_DESCRIBE))
summary(d_gender)
levels(dat_use1$GENID_DESCRIBE)
d_region <- data.frame(model.matrix(~ dat_use1$REGION))
summary(d_region)
levels(dat_use1$REGION)
d_vaxx <- data.frame(model.matrix(~ dat_use1$vaxx))
summary(d_vaxx)
list(d_vaxx)
summary(dat_use1$vaxx)
d_onsite <- data.frame(model.matrix(~ dat_use1$Works_onsite))
summary(d_onsite)
dat_for_analysis_sub <- data.frame(
  d_vaxx[,2],
  dat_use1$TBIRTH_YEAR[!is.na(dat_use1$vaxx)],
  d_educ[!is.na(dat_use1$vaxx),2:7],
  d_marstat[!is.na(dat_use1$vaxx),2:6],
  d_race[!is.na(dat_use1$vaxx),2:4],
  d_hispanic[!is.na(dat_use1$vaxx),2],
  d_gender[!is.na(dat_use1$vaxx),2:5],
  d_region[!is.na(dat_use1$vaxx),2:4],
  d_onsite[!is.na(dat_use1$Works_onsite),2:3])
summary(dat_for_analysis_sub)
names(dat_for_analysis_sub) <- sub("dat_use1.","",names(dat_for_analysis_sub))
summary(names(dat_for_analysis_sub))
summary(dat_for_analysis_sub)
names(dat_for_analysis_sub)[1] <- "vaxx"
summary(dat_for_analysis_sub)
names(dat_for_analysis_sub)[2] <- "TBIRTH_YEAR"
names(dat_for_analysis_sub)[17] <- "Hispanic"

#The goal here is to keep the regression parameters in a similar scale, and ensure that the intercept represents the corrected mean, this way the output of the regression will be easier to interpret.Following, we split into training and test sets,

require("standardize")
set.seed(1)
NN <- length(dat_for_analysis_sub$vaxx)
restrict_1 <- (runif(NN) < 0.5)
summary(restrict_1)
dat_train <- subset(dat_for_analysis_sub, restrict_1)
dat_test <- subset(dat_for_analysis_sub,!restrict_1)
sobj <- standardize(vaxx ~ TBIRTH_YEAR + EEDUCsome.hs + EEDUCHS.diploma + EEDUCsome.coll + EEDUCassoc.deg + EEDUCbach.deg + EEDUCadv.deg +
                      MSmarried + MSwidowed + MSdivorced + MSseparated + MSnever + RRACEBlack + RRACEAsian + RRACEOther +
                      Hispanic+ GENID_DESCRIBEmale + GENID_DESCRIBEfemale + GENID_DESCRIBEtransgender + GENID_DESCRIBEother +
                      REGIONSouth + REGIONMidwest + REGIONWest + Works_onsiteworked.onsite + Works_onsiteno
                    , data = dat_train, family = binomial)
summary(sobj$data)
s_dat_test <- predict(sobj, dat_test)
summary(s_dat_test)

#The goal with this model is to understand how to call the standardized objects from above and interpret the results with the “traditional model” of linear regression. The lm function.

model_lpm1 <- lm(sobj$formula, data = sobj$data)
summary(model_lpm1)
```
pred_vals_lpm <- predict(model_lpm1, s_dat_test)
```{r}
pred_model_lpm1 <- (pred_vals_lpm > mean(pred_vals_lpm))
table(pred = pred_model_lpm1, true = dat_test$vaxx)

# logit 
model_logit1 <- glm(sobj$formula, family = binomial, data = sobj$data)
summary(model_logit1)
table(pred = pred_model_logit1, true = dat_test$vaxx)
```
pred_vals <- predict(model_logit1, s_dat_test, type = "response")
```{r}
pred_model_logit1 <- (pred_vals > 0.5)
table(pred = pred_model_logit1, true = dat_test$vaxx)
summary(sobj$data)
```

